mean_cost <- mean(df$cost_num, na.rm = TRUE)
median_cost <- median(df$cost_num, na.rm = TRUE)
mean_rating <- mean(df$rating_num, na.rm = TRUE)
median_rating <- median(df$rating_num, na.rm = TRUE)
mean_votes <- mean(df$votes, na.rm = TRUE)
median_votes <- median(df$votes, na.rm = TRUE)
cat("\n--- Calculated Averages ---\n")
cat("Average Cost for Two (Mean):", mean_cost, "\n")
cat("Median Cost for Two:", median_cost, "\n")
cat("Average Rating (Mean):", mean_rating, "\n")
cat("Median Rating:", median_rating, "\n")
cat("Average Votes (Mean):", mean_votes, "\n")
cat("Median Votes:", median_votes, "\n")
